### ISSUE TITLE
[ISSUE] sometimes force closed when minimized

### ISSUE THREAD

**Issue by daniggtq** [Spegeli/PokemoGoBot-GottaCatchEmAll#54]
run 4 instance at times, rarely force closed 2/4 whithout warning ??

**Comment by Spegeli** [comment]
never saw such a "crash".
please take a look into the log files and let me know if there is any crash report there.

**Comment by trana315** [comment]
Forced close too. Check log, no error messages.

**Comment by PeterPlanlos** [comment]
i had same issue, seems to be a multi instance error. 
try rename the bot 
bot.exe
bot.exe.config
bot.pdb

keep exact file extensions or you will get errors on startup.

since i done this the bot (All instances) run well.

if you want to knwo whats up (when you dont rename the bot)
its like an error
InvalidResponseException from HttpClientExtensions.cs
seems it cant handle exceptions well on a multi instance when the exe is multiple times open..

hope it helps
