### ISSUE TITLE
Keep X best with CP & IV

### ISSUE THREAD

**Issue by ilihack** [Spegeli/PokemoGoBot-GottaCatchEmAll#98]
i think the better ist to Keep the Best Pokemon Perfektion AND one with the Best WP.
Nobody will be sad because the Transfer :)

**Comment by DuilioFrancis** [comment]
I agree. I'm trying to keep the best IV% and the best CP but I can't. Awesome bot anyway!!! Ty

**Comment by ZoDdarT** [comment]
I agree to!

**Comment by Spegeli** [comment]
The Question: Which Pokemon to Keep when you have to with 100% IV? or the same CP?

**Comment by Spegeli** [comment]
> hpbaxx commented 2 days ago
> Is it possible to set two "keep duplicates" for the following?
> 
> >minIV and/or >minCP (KeepDuplicateAmount1)
> <minIV and/or <minCP (KeepDuplicateAmount2)
> example: KeepDuplicateAmount1 to 5 and KeepDuplicateAmount2 to 0
> so it transfers all but 5 with >minIV and/or >minCP,
> but transfers all that neither match minIV nor minCP

**Comment by XiaoL0609** [comment]
@Spegeli hello spegeli, im looking for cooperation with Pokemon BOT developer. if u interested with it . add me on skype：XiaoL0609

**Comment by ilihack** [comment]
nice thank you @Spegeli 
by the way: very nice bot :)

**Comment by Spegeli** [comment]
Added to the latest Version: https://github.com/Spegeli/PokemoGoBot-GottaCatchEmAll/commit/6a691f238dc59b353012573f48bb776b3e1aea11

[ADDED] User can specify number of max IV and number of max CP pokemons to keep for each family - #340
TransferPokemonKeepDuplicateAmount get removed, instead we have now 2 new options:
TransferPokemonKeepAmountHighestCP = Keep X Highest Pokemon based on CP (when doing Transfer) - Default 0 (because CP are useless)
TransferPokemonKeepAmountHighestIV = Keep X Highest Pokemon based on IV (when doing Transfer) - Default 1
